module.exports = {
    EMW: {
        'emw-basic': {
            desc: 'EMW basic mesh template',
            lines: [
                'IOControls {',
                '\tEnableSections',
                '\tVerbosity = 3',
                '}',
                '',
                'Tensor {',
                '  EMW {',
                '    wavelength = ${1:wavelength}',
                '    parameter filename = "${2:parameter}"',
                '    CRI WavelengthDep  Real  Imag',
                '    NPW = 10 * nodes per wavelength in all directions',
                '    # NPWX = 10',
                '    # NPWY = 10',
                '    # NPWZ = 15',
                '    Grading off',
                '  }',
                '}',
            ],
        },
        'emw-advanced': {
            desc: 'EMW advanced mesh with MESH and CRI options',
            lines: [
                'IOControls {',
                '\tEnableSections',
                '\tVerbosity = 3',
                '}',
                '',
                'Tensor {',
                '  # MESH {',
                '  #   MinCellSize  = 0.01',
                '  #   MinCellSize direction "${3:material}" "x" 0.01',
                '  #   xCuts = (${5:x1} ${6:x2} ...)',
                '  # }',
                '  EMW {',
                '    wavelength = ${1:wavelength}',
                '    parameter filename = "${2:parameter}"',
                '    CRI WavelengthDep  Real  Imag',
                '    # CRI material "${3:material}" WavelengthDep  Real  Imag',
                '    # CRI region "${4:region}" WavelengthDep  Real  Imag',
                '    # CRI material "${3:material}" CRIMODEL "${7:CRIMI}"',
                '    NPW = 10 * nodes per wavelength in all directions',
                '    # NPW material "${3:material}" 15',
                '    # NPW region "${4:region}" 15',
                '    Grading off',
                '  }',
                '}',
            ],
        },
    },
};
