module.exports = {
    Contact: {
        Body: {
            desc: 'Assign contact to all surface elements of a region containing a point',
            lines: [
                '; Assign a contact to all surface elements (2d: edges, 3d: faces)',
                '; of the region which contains the given point, then delete the region',
                '(define CONT ${1:contact_name})',
                '(define POINT (position ${2:x} ${3:y} ${4:z}))',
                '(sdegeo:define-contact-set CONT 4.0 (color:rgb 1.0 0.0 0.0) "##")',
                '(sdegeo:set-contact (find-body-id POINT) CONT "remove")',
            ],
        },
        'Edge-Face': {
            desc: 'Assign contact to an element (2d: edge, 3d: face) at a point',
            lines: [
                '; Assign a contact to an element at a given point',
                '(define CONT ${1:contact_name})',
                '(define POINT (position ${2:x} ${3:y} ${4:z}))',
                '(sdegeo:define-contact-set CONT 4.0 (color:rgb 1.0 0.0 0.0) "##")',
                '; 2D:',
                '(sdegeo:set-contact (find-edge-id POINT) CONT)',
                '; 3D:',
                '; (sdegeo:set-contact (find-face-id POINT) CONT)',
            ],
        },
        'Interface-3d': {
            desc: 'Assign contact to common faces of two 3D regions',
            lines: [
                '; Assign contact to the common faces of two 3D regions',
                '(define CONT ${1:contact_name})',
                '(sdegeo:define-contact-set CONT 4.0 (color:rgb 1.0 0.0 0.0) "##")',
                '(set-interface-contact "${2:region1}" "${3:region2}" CONT)',
            ],
        },
    },
    Doping: {
        'Const-box': {
            desc: 'Constant doping profile in a box-shaped area',
            lines: [
                '; Constant doping profile in a box-shaped area',
                '(define NAME ${1:name})',
                '(sdedr:define-refeval-window (string-append "RW." NAME)',
                '    ${2|"Rectangle","Cuboid"|}',
                '    (position ${3:x0} ${4:y0} ${5:z0}) (position ${6:x1} ${7:y1} ${8:z1}))',
                '(sdedr:define-constant-profile (string-append "DC." NAME)',
                '    ${9|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|} ${10:1e15})',
                '(sdedr:define-constant-profile-placement (string-append "CPP." NAME)',
                '    (string-append "DC." NAME) (string-append "RW." NAME)',
                '    ${11:0.02} ${12|"replace","no_replace"|})',
            ],
        },
        'Const-material': {
            desc: 'Constant doping profile in a given material',
            lines: [
                '; Constant doping profile in a given material',
                '(define NAME ${1:name})',
                '(sdedr:define-constant-profile (string-append "DC." NAME)',
                '    ${2|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|} ${3:1e15})',
                '(sdedr:define-constant-profile-material (string-append "CPM." NAME)',
                '    (string-append "DC." NAME) "${4:Silicon}" ${5:0.02} ${6|"Replace","ReplaceLocal"|})',
            ],
        },
        'Const-region': {
            desc: 'Constant doping profile in a region',
            lines: [
                '; Constant doping profile in a region',
                '(define NAME ${1:name})',
                '(sdedr:define-constant-profile (string-append "DC." NAME)',
                '    ${2|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|} ${3:1e15})',
                '(sdedr:define-constant-profile-region (string-append "CPM." NAME)',
                '    (string-append "DC." NAME) "${4:region}" ${5:0.02} ${6|"Replace","ReplaceLocal"|})',
            ],
        },
        Gauss: {
            desc: 'Gaussian analytic doping profile',
            lines: [
                '; Gaussian analytic profile',
                '(define NAME ${1:name})',
                '(sdedr:define-refeval-window (string-append "RW." NAME)',
                '    ${2|"Line","Rectangle"|}',
                '    (position ${3:x0} ${4:y0} ${5:z0})',
                '    (position ${6:x1} ${7:y1} ${8:z1}))',
                '(sdedr:define-gaussian-profile (string-append "GAUSS." NAME)',
                '    ${9|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|}',
                '    "PeakPos" ${10:0}  "PeakVal" ${11:1e20}',
                '    "ValueAtDepth" ${12:1e15} "Depth" ${13:0.1}',
                '    "Gauss"  "Factor" 1.0)',
                '(sdedr:define-analytical-profile-placement (string-append "IMP." NAME)',
                '    (string-append "GAUSS." NAME) (string-append "RW." NAME)',
                '    ${14|"Positive","Negative","Both"|}',
                '    "NoReplace" "Eval")',
            ],
        },
        Submesh: {
            desc: 'Place an external doping profile (submesh) into a box-shaped region',
            lines: [
                '; Place an external doping profile (submesh) into a box-shaped region',
                '(define NAME ${1:name})',
                '(sdedr:define-submesh (string-append "SM." NAME) "${2:tdr_file}")',
                '(sdedr:define-refeval-window (string-append "RW." NAME)',
                '    ${3|"Rectangle","Cuboid"|}',
                '    (position ${4:x0} ${5:y0} ${6:z0}) (position ${7:x1} ${8:y1} ${9:z1}))',
                '(sdedr:define-submesh-placement (string-append "PSM." NAME)',
                '    (string-append "SM." NAME)',
                '    (string-append "RW." NAME) "Replace"',
                '    "AttachPoint" (position 0 0 0) "ToPoint" (position 0 0 0))',
            ],
        },
    },
    Meshing: {
        'Ref-box': {
            desc: 'Box-shaped refinement specification',
            lines: [
                '; Creating a box-shaped refinement specification',
                '(define RNAME "${1:rname}")',
                '(sdedr:define-refeval-window (string-append "RW." RNAME)',
                '    ${2|"Rectangle","Cuboid"|}',
                '    (position ${3:x0} ${4:y0} ${5:z0})  (position ${6:x1} ${7:y1} ${8:z1}))',
                '(sdedr:define-refinement-size (string-append "RS." RNAME)',
                '    ${9:dxmax} ${10:dymax} ${11:dzmax}',
                '    ${12:dxmin} ${13:dymin} ${14:dzmin})',
                '; (sdedr:define-refinement-function (string-append "RS." RNAME)',
                ';   "DopingConcentration" "MaxTransDiff" 1.0)',
                '(sdedr:define-refinement-placement (string-append "RP." RNAME)',
                '    (string-append "RS." RNAME) (string-append "RW." RNAME))',
            ],
        },
        'Ref-material': {
            desc: 'Refinement specification for a given material',
            lines: [
                '; Creating a refinement specification for a given material',
                '(define MNAME "${1:material_name}")',
                '(sdedr:define-refinement-size (string-append "RS." MNAME)',
                '    ${2:dxmax} ${3:dymax} ${4:dzmax}',
                '    ${5:dxmin} ${6:dymin} ${7:dzmin})',
                '; (sdedr:define-refinement-function (string-append "RS." MNAME)',
                ';   "DopingConcentration" "MaxTransDiff" 1.0)',
                '(sdedr:define-refinement-material (string-append "RP." MNAME)',
                '    (string-append "RS." MNAME) MNAME)',
            ],
        },
        'Ref-region': {
            desc: 'Refinement specification for a given region',
            lines: [
                '; Creating a refinement specification for a given region',
                '(define RNAME "${1:region_name}")',
                '(sdedr:define-refinement-size (string-append "RS." RNAME)',
                '    ${2:dxmax} ${3:dymax} ${4:dzmax}',
                '    ${5:dxmin} ${6:dymin} ${7:dzmin})',
                '; (sdedr:define-refinement-function (string-append "RS." RNAME)',
                ';   "DopingConcentration" "MaxTransDiff" 1.0)',
                '(sdedr:define-refinement-region (string-append "RP." RNAME)',
                '    (string-append "RS." RNAME) RNAME)',
            ],
        },
    },
};
