module.exports = {
    Contact: {
        Body: {
            desc: 'Assign contact to all surface elements of a region containing a point',
            lines: [
                '; - Assign a user-given contact to all surface elements (2d: edges, 3d: faces)',
                '; - of the region which contains the user-given point',
                '; - and delete the region itself.',
                '(define ${1:CONT} ${2:contact_name})',
                '(define ${3:POINT} (position x y z))',
                '(sdegeo:define-contact-set ${1:CONT} 4.0 (color:rgb 1.0 0.0 0.0) "##")',
                '(sdegeo:set-contact (find-body-id ${3:POINT}) ${1:CONT} "remove")',
            ],
        },
        'Edge-Face': {
            desc: 'Assign contact to an element (2d: edge, 3d: face) at a point',
            lines: [
                '; - Assign a user-given contact to an element (2d: edges, 3d: faces)',
                '; - of the user-given point',
                '(define ${1:CONT} ${2:contact_name})',
                '(define ${3:POINT} (position x y z))',
                '(sdegeo:define-contact-set ${1:CONT} 4.0 (color:rgb 1.0 0.0 0.0) "##")',
                '; - 2D:',
                '(sdegeo:set-contact (find-edge-id ${3:POINT}) ${1:CONT})',
                '; - 3D:',
                '; (sdegeo:set-contact (find-face-id ${3:POINT}) ${1:CONT})',
            ],
        },
        'Interface-3d': {
            desc: 'Assign contact to common faces of two 3D regions',
            lines: [
                '; - Assigns a contact to the common faces of two 3D regions.',
                '(define ${1:CONT} ${2:contact_name})',
                '(sdegeo:define-contact-set ${1:CONT} 4.0 (color:rgb 1.0 0.0 0.0) "##")',
                '(set-interface-contact "${3:region1}" "${4:region2}" ${1:CONT})',
            ],
        },
    },
    Doping: {
        'Const-box': {
            desc: 'Constant doping profile in a box-shaped area',
            lines: [
                '; Constant doping profile in a box-shaped area',
                '(define ${1:NAME} ${2:name})',
                '(sdedr:define-refeval-window (string-append "RW." ${1:NAME})',
                '    ${3|"Rectangle","Cuboid"|}',
                '    (position x0 y0 z0) (position x1 y1 z1))',
                '; - Common dopants:',
                '; "PhosphorusActiveConcentration" | "ArsenicActiveConcentration"',
                '; | "BoronActiveConcentration"',
                '(sdedr:define-constant-profile (string-append "DC." ${1:NAME})',
                '    ${4|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|} ${5:1e15})',
                '(sdedr:define-constant-profile-placement (string-append "CPP." ${1:NAME})',
                '    (string-append "DC." ${1:NAME}) (string-append "RW." ${1:NAME})',
                '    [${6:0.02}] [${7|"replace","no_replace"|}])',
            ],
        },
        'Const-material': {
            desc: 'Constant doping profile in a given material',
            lines: [
                '; Constant doping profile in a given material',
                '(define ${1:NAME} ${2:name})',
                '; - Common dopants:',
                '; "PhosphorusActiveConcentration" | "ArsenicActiveConcentration"',
                '; | "BoronActiveConcentration"',
                '(sdedr:define-constant-profile (string-append "DC." ${1:NAME})',
                '    ${3|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|} ${4:1e15})',
                '(sdedr:define-constant-profile-material (string-append "CPM." ${1:NAME})',
                '    (string-append "DC." ${1:NAME}) "${5:Silicon}" [${6:0.02}] [${7|"Replace","ReplaceLocal"|}])',
            ],
        },
        'Const-region': {
            desc: 'Constant doping profile in a region',
            lines: [
                '; Constant doping profile in a region',
                '(define ${1:NAME} ${2:name})',
                '; - Common dopants:',
                '; "PhosphorusActiveConcentration" | "ArsenicActiveConcentration"',
                '; | "BoronActiveConcentration"',
                '(sdedr:define-constant-profile (string-append "DC." ${1:NAME})',
                '    ${3|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|} ${4:1e15})',
                '(sdedr:define-constant-profile-region (string-append "CPM." ${1:NAME})',
                '    (string-append "DC." ${1:NAME}) "${5:region}" [${6:0.02}] [${7|"Replace","ReplaceLocal"|}])',
            ],
        },
        Gauss: {
            desc: 'Gaussian analytic doping profile',
            lines: [
                '; Gaussian analytic profile',
                '(define ${1:NAME} "${2:name}")',
                '(sdedr:define-refeval-window (string-append "RW." ${1:NAME})',
                '    ${3|"Line","Rectangle"|}',
                '    (position x0 y0 z0)',
                '    (position x1 y1 z1))',
                '; - Common dopants:',
                '; "PhosphorusActiveConcentration" | "ArsenicActiveConcentration"',
                '; | "BoronActiveConcentration"',
                '(sdedr:define-gaussian-profile (string-append "GAUSS." ${1:NAME})',
                '    ${4|"PhosphorusActiveConcentration","ArsenicActiveConcentration","BoronActiveConcentration"|}',
                '    "PeakPos" ${5:0}  "PeakVal" ${6:1e20}',
                '    "ValueAtDepth" ${7:1e15} "Depth" ${8:0.1}',
                '    "Gauss"  "Factor" 1.0)',
                '(sdedr:define-analytical-profile-placement (string.append "IMP." ${1:NAME})',
                '    (string.append "GAUSS." ${1:NAME}) (string.append "RW." ${1:NAME})',
                '    ${9|"Positive","Negative","Both"|}',
                '    "NoReplace" "Eval")',
            ],
        },
        Submesh: {
            desc: 'Place an external doping profile (submesh) into a box-shaped region',
            lines: [
                '; Place an external doping profile ("submesh") into a box-shaped region',
                '(define ${1:NAME} ${2:name})',
                '(sdedr:define-submesh (string-append "SM." ${1:NAME}) "${3:tdr_file}")',
                '(sdedr:define-refeval-window (string-append "RW." ${1:NAME})',
                '    ${4|"Rectangle","Cuboid"|}',
                '    (position x0 y0 z0) (position x1 y1 z1))',
                '(sdedr:define-submesh-placement (string-append "PSM." ${1:NAME})',
                '    (string-append "SM." ${1:NAME})',
                '    (string-append "RW." ${1:NAME}) "Replace"',
                '    "AttachPoint" (position 0 0 0) "ToPoint" (position 0 0 0))',
            ],
        },
    },
    Meshing: {
        'Ref-box': {
            desc: 'Box-shaped refinement specification',
            lines: [
                '; Creating a box-shaped refinement specification',
                '(define ${1:RNAME} "${2:rname}")',
                '(sdedr:define-refeval-window (string-append "RW." ${1:RNAME})',
                '    ${3|"Rectangle","Cuboid"|}',
                '    (position x0 y0 z0)  (position x1 y1 z1))',
                '(sdedr:define-refinement-size (string-append "RS." ${1:RNAME})',
                '    ${4:dxmax} ${5:dymax} [${6:dzmax}]',
                '    ${7:dxmin} ${8:dymin} [${9:dzmin}])',
                '; (sdedr:define-refinement-function (string-append "RS." ${1:RNAME})',
                ';   "DopingConcentration" "MaxTransDiff" 1.0)',
                '(sdedr:define-refinement-placement (string-append "RP." ${1:RNAME})',
                '    (string-append "RS." ${1:RNAME}) (string-append "RW." ${1:RNAME}))',
            ],
        },
        'Ref-material': {
            desc: 'Refinement specification for a given material',
            lines: [
                '; Creating a refinement specification for a given material',
                '(define ${1:MNAME} "${2:material_name}")',
                '(sdedr:define-refinement-size (string-append "RS." ${1:MNAME})',
                '    ${3:dxmax} ${4:dymax} [${5:dzmax}]',
                '    ${6:dxmin} ${7:dymin} [${8:dzmin}])',
                '; (sdedr:define-refinement-function (string-append "RS." ${1:MNAME})',
                ';   "DopingConcentration" "MaxTransDiff" 1.0)',
                '; (sdedr:define-refinement-function (string-append "RS." ${1:MNAME})',
                ';   "MaxLenInt" "material1" "material2" ref-size factor)',
                '(sdedr:define-refinement-material (string-append "RP." ${1:MNAME})',
                '    (string-append "RS." ${1:MNAME}) ${1:MNAME})',
            ],
        },
        'Ref-region': {
            desc: 'Refinement specification for a given region',
            lines: [
                '; Creating a refinement specification for a given region',
                '(define ${1:RNAME} "${2:region_name}")',
                '(sdedr:define-refinement-size (string-append "RS." ${1:RNAME})',
                '    ${3:dxmax} ${4:dymax} [${5:dzmax}]',
                '    ${6:dxmin} ${7:dymin} [${8:dzmin}])',
                '; (sdedr:define-refinement-function (string-append "RS." ${1:RNAME})',
                ';   "DopingConcentration" "MaxTransDiff" 1.0)',
                '; (sdedr:define-refinement-function (string-append "RS." ${1:RNAME})',
                ';   "MaxLenInt" "material1" "material2" ref-size factor)',
                '(sdedr:define-refinement-region (string-append "RP." ${1:RNAME})',
                '    (string-append "RS." ${1:RNAME}) ${1:RNAME})',
            ],
        },
    },
};
