module.exports = {
    CurrentPlot: {
        CurrentPlot: {
            desc: 'CurrentPlot output variables template',
            lines: [
                'CurrentPlot {',
                '  hDensity((0.0 1.0)) * hole density at position (0um, 1um)',
                '  ElectricField/Vector((0.0 1.0)) * Electric Field Vector',
                '  Potential (',
                '    Average(Region="Channel") * average over a region',
                '    Average(Everywhere) * average over entire device',
                '    Maximum(Material="Oxide") * Maximum in a material',
                '    Maximum(Semiconductor) * in all semiconductors',
                '    * minimum in a material and a region, output under the name "x":',
                '    Minimum(Name="x" Material="Oxide" Region="Channel")',
                '    * minimum in a region and all insulator regions:',
                '    Minimum(Region="Channel" Insulator)',
                '  )',
                '  eDensity(',
                '    * maximum and coordinates of maximum over semiconductors',
                '    Maximum(Semiconductor Coordinates)',
                '    * average and coordinates of centroid',
                '    Average(Semiconductor Coordinates)',
                '    * minimum and coordinates of minimum over semiconductors',
                '    Minimum(Semiconductor Coordinates)',
                '    * maximum and coordinates of maximum in well',
                '    Maximum(DopingWell(-0.1 0.3) Coordinates)',
                '    * integral over the semiconductor regions',
                '    Integrate(Semiconductor)',
                '  )',
                '  SpaceCharge(',
                '    * maximum over 2D window',
                '    Maximum(Window[(-0.2 0) (0.2 0.2)])',
                '    * average and average coordinates in window',
                '    Average(Window[(-0.1 0.3) (0.2 0.2)])',
                '    * integral over 2D window',
                '    Integrate(Window[(-0.1 0.3) (0.2 0.2)])',
                '    * integral over well',
                '    Integrate( DopingWell(-0.1 0.3) )',
                '  )',
                '}',
            ],
        },
    },
    Electrode: {
        Electrode: {
            desc: 'Electrical boundary conditions for device contacts',
            lines: [
                'Electrode {',
                '  { Name= "${1:name}"  Voltage= ${2:value} }',
                '  * Other common options:',
                '  { Name= "${1:name}"',
                '  # Resist= ${3:value} DistResist= ${4:value}',
                '  # Schottky Barrier= ${5:value} Workfunction= ${6:value}',
                '  # Current= ${7:value} Charge= ${8:value}',
                '  * Piecewise linear time-dependent voltage source',
                '  # Voltage= ( ${9:v0} at ${10:t0} , ${11:v1} at ${12:t1}, ... )',
                '  }',
                '}',
            ],
        },
    },
    File: {
        File: {
            desc: 'File I/O section for input/output paths',
            lines: [
                'File {',
                '\tGrid=      "@tdr@"',
                '\tParameter= "@parameter@"',
                '\tCurrent=   "@plot@"',
                '\tPlot=      "@tdrdat@"',
                '\tOutput=    "@log@"',
                '}',
            ],
        },
    },
    Math: {
        'Basic-Settings': {
            desc: 'Math extrapolation and convergence settings',
            lines: [
                '\tExtrapolate',
                '\tNotdamped=50',
                '\tIterations=15',
                '\tExitOnFailure',
            ],
        },
        'ErrorControl': {
            desc: 'Error control and damping parameters',
            lines: [
                '  Digits=5',
                '  ErrEff(electron)=1e10',
                '  ErrEff(hole)=1e10',
                '  # eDrForceRefDens= 1e12  * Damping parameters ',
                '  # hDrForceRefDens= 1e12  *   for high-field mobility driving force',
                '  # RelTermMinDensity= 1e3 * Stabilization parameters for temp. relax. term.',
                '  # RelTermMinDensityZero= 1e8 ',
                '  # ExitOnFailure',
            ],
        },
        Solver: {
            desc: 'Linear solver method selection',
            lines: [
                '  *- Single Device:',
                '  Method= Super     * Single device < 10k node/single processor',
                '  # Method= ParDiSo * Single device < 100k node/multi processor',
                '  # Method= ILS     * > 8k node/multi processor',
                '  # Number_of_Threads= ${1:int} # | maximum',
                '  # Number_of_Assembly_Threads= ${1:int}',
                '  # Number_of_Solver_Threads= ${1:int}',
                '  *- Multi-Device/Mixed Mode',
                '  # Method=Blocked',
                '  # SubMethod= Super # | ParDiSo | ILS',
            ],
        },
    },
    Physics: {
        BandGap: {
            desc: 'Band gap narrowing models',
            lines: [
                '  *- Common Band gap narrowing options:',
                '\tEffectiveIntrinsicDensity (',
                '\t  BandGapNarrowing (',
                '      Slotboom # | oldSlotboom | Slotboom | BennettWilson | delAlamo | TableBGN',
                '    )',
                '  )',
            ],
        },
        General: {
            desc: 'General physics settings (area factor, temperature)',
            lines: [
                '  AreaFactor= ${1:device-width}',
                '  Temperature= ${2:operating temp}',
            ],
        },
        Mobility: {
            desc: 'Mobility models including high-field saturation',
            lines: [
                '  Mobility(',
                '    *- Doping related mobility degradations:',
                '    PhuMob # | DopingDependence',
                '    *- High-Field Saturation:',
                '    # HighFieldSaturation | eHighFieldSaturation | hHighFieldSaturation',
                '    HighFieldSaturation ( ',
                '      *- Driving forces: ',
                '      GradQuasiFermi # | EparallelToInterface | CarrierTempDrive | Eparallel',
                '    )',
                '    *- Mobility degradation at interfaces:',
                '    Enormal(',
                '      # Lombardi | Lombardi_highk | UniBo',
                '    )',
                '  )',
            ],
        },
        Recombination: {
            desc: 'Recombination models (SRH, Auger, avalanche)',
            lines: [
                '  Recombination (',
                '    SRH (',
                '      DopingDependence  # TempDependence | ExpTempDependence',
                '    )',
                '    # Auger',
                '    # Band2Band (',
                '    #   Schenk | Hurkx | E1 | E1_5 | E2',
                '    # )',
                '    *- Avalanche generation:',
                '    # Avalanche | eAvalanche | hAvalanche',
                '    # Avalanche (',
                '    #   *- Avalanche generation options:',
                '    #   CarrierTempDrive # | GradQuasiFermi | Eparallel | vanOverstraeten | Okuto',
                '    # )',
                '    *- common setting:',
                '    eAvalanche (CarrierTempDrive)',
                '    hAvalanche (Eparallel)',
                '  )',
            ],
        },
        Traps: {
            desc: 'Trap-assisted recombination models',
            lines: [
                '  Traps (',
                '    * Trap Types:   FixedCharge, Acceptor, Donor, eNeutral, and hNeutral',
                '    ( Acceptor',
                '      * Energy distributions type: [Level | Uniform | Exponential | Gaussian | Table]',
                '      Level',
                '      * Energy reference point: [fromCondBand | fromMidBandGap | fromValBand]',
                '      fromMidBandGap',
                '      * Center of energy dist. with respect to the ref. point',
                '      EnergyMid= ${1:value}',
                '      * Width of the energy dist. (not used for "Level") ',
                '      EnergySig= ${2:value}',
                '      * Trap concentration',
                '      Conc= ${3:value}',
                '      eXsection=${4:value}',
                '      * Trap cross-sections to capture an electron/hole',
                '      eXsection=${4:value}  hXsection=${5:value}',
                '    )',
                '  )',
            ],
        },
        'ComplexRefractiveIndex': {
            desc: 'Complex refractive index (basic)',
            lines: [
                '    ComplexRefractiveIndex(',
                '      WavelengthDep(Real Imag)',
                '    )',
            ],
        },
        'ComplexRefractiveIndex (Advanced)': {
            desc: 'Complex refractive index (advanced options)',
            lines: [
                '    ComplexRefractiveIndex(',
                '      WavelengthDep(Real Imag)',
                '      # CarrierDep(Real Imag)',
                '      # TemperatureDep(Real)',
                '      # GainDep(Real(lin)) # | Real(log)',
                '      # CRIModel(Name="${1:CRIMI filename w/o extension}")',
                '    )',
            ],
        },
        Excitation: {
            desc: 'Optical excitation (basic)',
            lines: [
                '    Excitation(',
                '      fromTop * | fromBottom',
                '      Wavelength = 0.6 * [um]',
                '      Intensity = 0.1 * [W/cm2]',
                '      # Theta = 0  ',
                '      Polarization = TE # | TM ',
                '      # PolarizationAngle = 0 * angle between H and zxk',
                '    )',
            ],
        },
        'Excitation (Advanced)': {
            desc: 'Optical excitation (advanced with window options)',
            lines: [
                '    Excitation(',
                '      Wavelength = 0.6 * [um]',
                '      Intensity = 0.1 * [W/cm2]',
                '      Theta = 0  * 2D: in +y direction. 3D: +z.',
                '      Phi = 0 * 0 in +x direction, towards y.',
                '      Polarization = TE # | TM ',
                '      Window(',
                '        Line( * 2D only',
                '          x1=0 x2=1',
                '        )',
                '        # Rectangle( * 3D only',
                '        #   Corner1=(0 0) Corner2=(1 1)',
                '        # )',
                '      )',
                '    )',
            ],
        },
        'OpticalGeneration': {
            desc: 'Optical generation (basic)',
            lines: [
                '    OpticalGeneration (',
                '      QuantumYield(',
                '        StepFunction(',
                '          Bandgap # EffectiveBandgap | Wavelength = ... | Energy = ...',
                '        )',
                '      )',
                '      ComputeFromMonochromaticSource(scaling=1)',
                '    )',
            ],
        },
        'OpticalGeneration (Advanced)': {
            desc: 'Optical generation (advanced with spectrum and transient)',
            lines: [
                '    OpticalGeneration (',
                '      QuantumYield(',
                '        StepFunction(',
                '          Bandgap',
                '        )',
                '      )',
                '      ComputeFromMonochromaticSource',
                '      # ComputeFromSpectrum(',
                '      #   Select( Condition = "0.3 <= $wavelength && $wavelength <= 1.2" )',
                '      #   Scaling = ${1:factor}',
                '      #   TimeDependence(',
                '      #     Scaling = ${1:factor}',
                '      #     WaveTime = (${2:t1}, ${3:t2})',
                '      #   )',
                '      # )',
                '      SetConstant = ${4:G} * [1/cm3s]',
                '    )',
            ],
        },
        'OpticalSolver-OptBeam': {
            desc: 'Optical solver OptBeam (basic)',
            lines: [
                '    OpticalSolver(',
                '      OptBeam(',
                '        LayerStackExtraction()',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-OptBeam (Advanced)': {
            desc: 'Optical solver OptBeam (advanced)',
            lines: [
                '    OpticalSolver(',
                '      OptBeam(',
                '        LayerStackExtraction(',
                '          # Position = (x,y,z)',
                '          # WindowName = "${1:window}"',
                '          Mode = Regionwise # | Elementwise',
                '          # ComplexRefractiveIndexThreshold = 0.01',
                '        )',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-Raytracer': {
            desc: 'Optical solver RayTracing (basic)',
            lines: [
                '    OpticalSolver(',
                '      RayTracing(',
                '        DepthLimit = 1e4',
                '        MinIntensity = 1e-4',
                '        MonteCarlo',
                '        PlotInterfaceFlux',
                '        RayDistribution(',
                '          Mode = Autopopulate # | MonteCarlo',
                '          NumberOfRays = 1000',
                '        )',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-Raytracer (Advanced)': {
            desc: 'Optical solver RayTracing (advanced with farfield)',
            lines: [
                '    OpticalSolver(',
                '      RayTracing(',
                '        DepthLimit = 1e4',
                '        MinIntensity = 1e-4',
                '        MonteCarlo',
                '        PlotInterfaceFlux',
                '        RayDistribution(',
                '          Mode = Autopopulate # | MonteCarlo',
                '          NumberOfRays = 1000',
                '          # Dx = ${1:dx}',
                '          # Dy = ${2:dy}',
                '          # WindowName = "${3:window}"',
                '        )',
                '        Farfield(',
                '          Discretization = 360',
                '          Sensor(',
                '            Angular(',
                '              Phi = (0 360)',
                '              Theta = (0 90)',
                '            )',
                '          )',
                '        )',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-TMM': {
            desc: 'Optical solver TMM (basic)',
            lines: [
                '    OpticalSolver(',
                '      TMM(',
                '        IntensityPattern = StandingWave # | Envelope',
                '        LayerStackExtraction(',
                '          Medium(',
                '            Location = bottom # | top',
                '            Material = "${1:material}"',
                '          )',
                '        )',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-TMM (Advanced)': {
            desc: 'Optical solver TMM (advanced with medium options)',
            lines: [
                '    OpticalSolver(',
                '      TMM(',
                '        IntensityPattern = StandingWave # | Envelope',
                '        LayerStackExtraction(',
                '          Medium(',
                '            Location = bottom # | top',
                '            Material = "${1:material}"',
                '            # RefractiveIndex = ${2:n}',
                '            # ExtinctionCoefficient = ${3:k}',
                '          )',
                '          # Position = (x,y,z)',
                '          # WindowName = "${4:window}"',
                '        )',
                '      )',
                '    )',
            ],
        },
    },
    Plot: {
        'Basic-Set': {
            desc: 'Basic set of plot output variables',
            lines: [
                '  eDensity hDensity ',
                '  Current eCurrent  hCurrent',
                '  Potential  SpaceCharge  ElectricField',
                '  eMobility  hMobility  eVelocity  hVelocity',
                '  Doping DonorConcentration AcceptorConcentration',
            ],
        },
        'Extensive-Set': {
            desc: 'Extensive set of plot output variables',
            lines: [
                '  *- Carrier Densities:',
                '  eDensity hDensity',
                '  # EffectiveIntrinsicDensity IntrinsicDensity',
                '  *- Currents and current components:',
                '  Current/Vector eCurrent/Vector hCurrent/Vector',
                '  # ConductionCurrent/Vector DisplacementCurrent/Vector',
                '  eMobility hMobility',
                '  eVelocity hVelocity',
                '  *- Fields, Potentials and Charge distributions',
                '  ElectricField/Vector',
                '  Potential',
                '  eQuasiFermi hQuasiFermi',
                '  SpaceCharge',
                '  *- Driving forces',
                '  eGradQuasiFermi/Vector hGradQuasiFermi/Vector',
                '  eEparallel hEparallel ',
                '  eENormal hENormal',
                '  *- Temperatures',
                '  LatticeTemperature',
                '  eTemperature hTemperature',
                '  *- Generation/Recombination',
                '  SRHRecombination Band2BandGeneration AugerRecombination',
                '  AvalancheGeneration eAvalancheGeneration hAvalancheGeneration',
                '  TotalRecombination',
                '  eLifeTime hLifeTime',
                '  SurfaceRecombination',
                '  *- Doping Profiles',
                '  Doping ',
                '  DonorConcentration AcceptorConcentration',
                '  *- Band structure',
                '  BandGap ',
                '  BandGapNarrowing',
                '  ElectronAffinity',
                '  ConductionBandEnergy ValenceBand',
                '  *- Optical',
                '  # ComplexRefractiveIndex AbsorbedPhotonDensity OpticalGeneration',
                '  *- Tunneling',
                '  # BarrierTunneling eBarrierTunneling hBarrierTunneling',
            ],
        },
    },
    Solve: {
        'Initial-Solve': {
            desc: 'Initial coupled solve (Poisson, then with carriers)',
            lines: [
                '  Coupled (Iterations= 100 LineSearchDamping= 1e-4){ Poisson ',
                '    * Other common options:',
                '    # eQuantumPotential hQuantumPotential',
                '  } ',
                '  Coupled (Iterations= 100){ Poisson Electron Hole',
                '    * Other common options: ',
                '    # eQuantumPotential hQuantumPotential eTemperature hTemperature Temperature',
                '  } ',
                '  Coupled (Iterations= 100){ Poisson Electron Hole Contact Circuit}',
            ],
        },
        QuasiStat: {
            desc: 'Quasistationary sweep (gate/drain voltage)',
            lines: [
                '  # NewCurrentFile="${1:filename-stem}"',
                '  Quasistationary ( ',
                '    InitialStep= 1e-2 Increment= 1.41',
                '    MinStep= 1e-7     MaxStep= 0.2',
                '    Goal { Name="${2:name}" Voltage= ${3:value} }',
                '  ){',
                '    Coupled { ',
                '      Poisson Electron Hole',
                '      # eQuantumPotential hQuantumPotential',
                '      # eTemperature hTemperature Temperature',
                '      # Contact Circuit',
                '    }',
                '    # CurrentPlot(Time=(Range=(0 1) Intervals=30))',
                '  }',
            ],
        },
        Transient: {
            desc: 'Transient simulation',
            lines: [
                '  # NewCurrentFile="${1:filename-stem}"',
                '  Transient (',
                '    InitialTime= ${2:value} FinalTime= ${3:value}',
                '    InitialStep= ${2:value} Increment= 1.41',
                '    Minstep= ${4:value} MaxStep= ${5:value}',
                '  ){',
                '    Coupled {',
                '      Poisson Electron Hole',
                '      # eQuantumPotential hQuantumPotential',
                '      # eTemperature hTemperature Temperature',
                '      # Contact Circuit',
                '    }',
                '  }',
            ],
        },
        ACcoupled: {
            desc: 'AC coupled small-signal analysis',
            lines: [
                '  Quasistationary (',
                '    InitialStep= 1e-2 Increment= 1.41',
                '    MinStep= 1e-7     MaxStep= 0.2',
                '    Goal { Parameter=${1:name}.dc Voltage= ${2:value} }',
                '  ){',
                '    ACCoupled (',
                '      StartFrequency= ${3:value} EndFrequency= ${4:value}',
                '      NumberOfPoints= ${5:int} [Decade | Linear]',
                '      Node(${6:list-of-nodes}) Exclude(${7:list-of-voltage-source-names}) ',
                '      ACCompute (Time = (Range = (0 1)  Intervals = ${5:int}))',
                '    ){',
                '      ${8:equations}',
                '    }',
                '  }',
            ],
        },
    },
    System: {
        System: {
            desc: 'System section for circuit, voltage sources, and devices',
            lines: [
                'File {',
                '  Output= "@log@"',
                '}',
                '',
                'Device ${1:dev-name} {',
                '  Electrode { ... }',
                '  File { ... }',
                '  Physics { ... }',
                '}',
                '',
                'System {',
                '  *- Voltage sources',
                '  Vsource_pset ${2:v-name} (${3:node1} ${4:node2}) { dc= ${5:value} }',
                '  Vsource_pset ${2:v-name} (${3:node1} ${4:node2}) { ',
                '    pulse= (${5:value}   * dc-offset',
                '      ${6:value}   * amplitude',
                '      ${7:value}   * td: initial delay',
                '      ${8:value}   * tr: rise time',
                '      ${9:value}   * tf: fall time',
                '      ${10:value}   * pw: pulse width',
                '      ${11:value})  * period',
                '  }',
                '  Vsource_pset ${2:v-name} (${3:node1} ${4:node2}) { ',
                '    pwl= ( ${12:t1} ${13:v1}  ${14:t2} ${15:v2} [...] )',
                '  }',
                '  *- Physical devices ',
                '  ${1:dev-name} ${16:instance-name} ( "${17:cont1}"= ${3:node1}  "${18:cont2}"= ${4:node2} [...] )',
                '  *- Lumped elements',
                '  Capacitor_pset ${19:c-name} ( ${3:node1} ${4:node2} ){ capacitance= ${20:value} }',
                '  Resistor_pset  ${21:r-name} ( ${3:node1} ${4:node2} ){ resistance= ${22:value} }',
                '  Inductor_pset  ${23:i-name} ( ${3:node1} ${4:node2} ){ inductance= ${24:value} }',
                '  *- Plotting',
                '  Plot "${25:file-name}.plt" (time() v(${26:node}) i(${27:element},${26:node}) [...] )',
                '}',
            ],
        },
    },
};
