module.exports = {
    CurrentPlot: {
        CurrentPlot: {
            desc: 'CurrentPlot output variables template',
            lines: [
                'CurrentPlot {',
                '  hDensity((0.0 1.0)) * hole density at position (0um, 1um)',
                '  ElectricField/Vector((0.0 1.0)) * Electric Field Vector',
                '  Potential (',
                '    Average(Region="Channel") * average over a region',
                '    Average(Everywhere) * average over entire device',
                '    Maximum(Material="Oxide") * Maximum in a material',
                '    Maximum(Semiconductor) * in all semiconductors',
                '    * minimum in a material and a region, output under the name "x":',
                '    Minimum(Name="x" Material="Oxide" Region="Channel")',
                '    * minimum in a region and all insulator regions:',
                '    Minimum(Region="Channel" Insulator)',
                '  )',
                '  eDensity(',
                '    * maximum and coordinates of maximum over semiconductors',
                '    Maximum(Semiconductor Coordinates)',
                '    * average and coordinates of centroid',
                '    Average(Semiconductor Coordinates)',
                '    * minimum and coordinates of minimum over semiconductors',
                '    Minimum(Semiconductor Coordinates)',
                '    * maximum and coordinates of maximum in well',
                '    Maximum(DopingWell(-0.1 0.3) Coordinates)',
                '    * integral over the semiconductor regions',
                '    Integrate(Semiconductor)',
                '  )',
                '  SpaceCharge(',
                '    * maximum over 2D window',
                '    Maximum(Window[(-0.2 0) (0.2 0.2)])',
                '    * average and average coordinates in window',
                '    Average(Window[(-0.1 0.3) (0.2 0.2)])',
                '    * integral over 2D window',
                '    Integrate(Window[(-0.1 0.3) (0.2 0.2)])',
                '    * integral over well',
                '    Integrate( DopingWell(-0.1 0.3) )',
                '  )',
                '}',
            ],
        },
    },
    Electrode: {
        Electrode: {
            desc: 'Electrical boundary conditions for device contacts',
            lines: [
                'Electrode {',
                '  { Name= "${1:name}"  Voltage= ${2:value [V]} }',
                '  * Other common options:',
                '  { Name= "${1:name}"',
                '  # Resist= ${3:value [Ohm um]} DistResist= ${4:value [Ohm cm^2]}',
                '  # Schottky Barrier= ${5:value [V]} Workfunction= ${6:value [V]}',
                '  # Current= ${7:value [A/um]} Charge= ${8:value [C]}',
                '  * Piecewise linear time-dependent voltage source',
                '  # Voltage= ( ${9:v0 [V]} at ${10:t0 [sec]} , ${11:v1 [V]} at ${12:t1 [sec]}, ... )',
                '  }',
                '}',
            ],
        },
    },
    File: {
        File: {
            desc: 'File I/O section for input/output paths',
            lines: [
                'File {',
                '\tGrid=      "@tdr@"',
                '\tParameter= "@parameter@"',
                '\tCurrent=   "@plot@"',
                '\tPlot=      "@tdrdat@"',
                '\tOutput=    "@log@"',
                '}',
            ],
        },
    },
    Math: {
        'Basic-Settings': {
            desc: 'Math extrapolation and convergence settings',
            lines: [
                '\tExtrapolate',
                '\tNotdamped=50',
                '\tIterations=15',
                '\tExitOnFailure',
            ],
        },
        'ErrorControl': {
            desc: 'Error control and damping parameters',
            lines: [
                '  Digits=5',
                '  ErrEff(electron)=1e10',
                '  ErrEff(hole)=1e10',
                '  # eDrForceRefDens= 1e12  * Damping parameters ',
                '  # hDrForceRefDens= 1e12  *   for high-field mobility driving force',
                '  # RelTermMinDensity= 1e3 * Stabilization parameters for temp. relax. term.',
                '  # RelTermMinDensityZero= 1e8 ',
                '  # ExitOnFailure',
            ],
        },
        Solver: {
            desc: 'Linear solver method selection',
            lines: [
                '  *- Single Device:',
                '  Method= Super     * Single device < 10k node/single processor',
                '  # Method= ParDiSo * Single device < 100k node/multi processor',
                '  # Method= ILS     * > 8k node/multi processor',
                '  # Number_of_Threads= ${1:int} # | maximum',
                '  # Number_of_Assembly_Threads= ${1:int}',
                '  # Number_of_Solver_Threads= ${1:int}',
                '  *- Multi-Device/Mixed Mode',
                '  # Method=Blocked',
                '  # SubMethod= Super # | ParDiSo | ILS',
            ],
        },
    },
    Physics: {
        BandGap: {
            desc: 'Band gap narrowing models',
            lines: [
                '  *- Common Band gap narrowing options:',
                '\tEffectiveIntrinsicDensity (',
                '\t  BandGapNarrowing (',
                '      Slotboom # | oldSlotboom | Slotboom | BennettWilson | delAlamo | TableBGN',
                '    )',
                '  )',
            ],
        },
        General: {
            desc: 'General physics settings (area factor, temperature)',
            lines: [
                '  AreaFactor= ${1:device-width [um]}',
                '  Temperature= ${2:operating temp. [K]}',
            ],
        },
        Mobility: {
            desc: 'Mobility models including high-field saturation',
            lines: [
                '  Mobility(',
                '    *- Doping related mobility degradations:',
                '    PhuMob # | DopingDependence',
                '    *- High-Field Saturation:',
                '    # HighFieldSaturation | eHighFieldSaturation | hHighFieldSaturation',
                '    HighFieldSaturation ( ',
                '      *- Driving forces: ',
                '      GradQuasiFermi # | EparallelToInterface | CarrierTempDrive | Eparallel',
                '    )',
                '    *- Mobility degradation at interfaces:',
                '    Enormal(',
                '      # Lombardi | Lombardi_highk | UniBo',
                '    )',
                '  )',
            ],
        },
        Recombination: {
            desc: 'Recombination models (SRH, Auger, avalanche)',
            lines: [
                '  Recombination (',
                '    SRH (',
                '      DopingDependence  # TempDependence | ExpTempDependence',
                '    )',
                '    # Auger',
                '    # Band2Band (',
                '    #   Schenk | Hurkx | E1 | E1_5 | E2',
                '    # )',
                '    *- Avalanche generation:',
                '    # Avalanche | eAvalanche | hAvalanche',
                '    # Avalanche (',
                '    #   *- Avalanche generation options:',
                '    #   CarrierTempDrive # | GradQuasiFermi | Eparallel | vanOverstraeten | Okuto',
                '    # )',
                '    *- common setting:',
                '    eAvalanche (CarrierTempDrive)',
                '    hAvalanche (Eparallel)',
                '  )',
            ],
        },
        Traps: {
            desc: 'Trap-assisted recombination models',
            lines: [
                '  Traps (',
                '    * Trap Types:   FixedCharge, Acceptor, Donor, eNeutral, and hNeutral',
                '    ( Acceptor',
                '      * Energy distributions type: [Level | Uniform | Exponential | Gaussian | Table]',
                '      Level',
                '      * Energy reference point: [fromCondBand | fromMidBandGap | fromValBand]',
                '      fromMidBandGap',
                '      * Center of energy dist. with respect to the ref. point',
                '      EnergyMid= ${1:value [eV]}',
                '      * Width of the energy dist. (not used for "Level") ',
                '      EnergySig= ${2:value [eV]}',
                '      * Trap concentration',
                '      Conc= ${3:value [1/cm^3]}',
                '      eXsection=${4:value [cm^2]}',
                '      * Trap cross-sections to capture an electron/hole',
                '      eXsection=${4:value [cm^2]}  hXsection=${5:value [cm^2]}',
                '    )',
                '  )',
            ],
        },
        'ComplexRefractiveIndex': {
            desc: 'Complex refractive index (basic)',
            lines: [
                '    ComplexRefractiveIndex(',
                '      WavelengthDep(Real Imag)',
                '    )',
            ],
        },
        'ComplexRefractiveIndex (Advanced)': {
            desc: 'Complex refractive index (advanced options)',
            lines: [
                '    ComplexRefractiveIndex(',
                '      WavelengthDep(Real Imag)',
                '      # CarrierDep(Real Imag)',
                '      # TemperatureDep(Real)',
                '      # GainDep(Real(lin)) # | Real(log)',
                '      # CRIModel(Name="${1:CRIMI filename w/o extension}")',
                '    )',
            ],
        },
        Excitation: {
            desc: 'Optical excitation (basic)',
            lines: [
                '    Excitation(',
                '      fromTop * | fromBottom excitation plane covers hole domain, see log to adjust other parameters like theta.',
                '      Wavelength = 0.6 * [um]',
                '      Intensity = 0.1 * [W/cm2]',
                '      # Theta = 0  ',
                '      Polarization = TE # | TM ',
                '      # PolarizationAngle = 0 * angle between H and zxk',
                '    )',
            ],
        },
        'Excitation (Advanced)': {
            desc: 'Optical excitation (advanced with window options)',
            lines: [
                '    Excitation(',
                '      Wavelength = 0.6 * [um]',
                '      Intensity = 0.1 * [W/cm2]',
                '      Theta = 0  * 2D: in +y direction. 3D: +z. (for DFISE)',
                '      # Theta = 90 * 2D: in +x direction. 3D: +x. (for UCS)',
                '      Phi = 0 * 0 in +x direction, towards y.',
                '      Polarization = TE # | TM ',
                '      # PolarizationAngle = 0 * angle between H and zxk',
                '      Window(',
                '        # Origin = (0 0 0) * global location of window coordinate system\'s (CS) origin',
                '        # OriginAnchor = Center # |North|South|West|East|NorthEast|SouthEast|NorthWest|SouthWest ',
                '        #                      * define which point of the window shape coincides with the Window CS origin',
                '        # xDirection = (1 0 0) * x-axis direction of window CS',
                '        # yDirection = (0 1 0) * y-axis direction of window CS',
                '        # RotationAngles = (<theta> <phi> <psi>) * alternative way to define window CS orientation',
                '        Line( * 2D only',
                '          x1=0 x2=1 * start, end point, defined in window CS.',
                '          # Dx=1 * line width, depends on originAnchor',
                '        )',
                '        # Rectangle( * 3D only',
                '        #   Corner1=(0 0) Corner2=(1 1) * start, end corner of rectangle, defined in window CS.',
                '        # #   Dx=1 Dy=1 * length in x and y direction, defined in window CS.',
                '        # )',
                '        # Circle(Radius=1) * 3D only, circle around origin.',
                '        # WeightedAPDIntegration * more accurate total absorption for 1D solvers, e.g. for moving windows.',
                '        # IntensityDistribution(',
                '        #   Gaussian(* spatial intensity profile',
                '        #     PeakPosition = (0, 0) * in window CS',
                '        #     PeakWidth = (0, 0) * plateau width in x and y direction in window CS',
                '        #     Length = (0, 0) * Length of Gaussian decay in x and y direction in window CS',
                '        #     # Sigma = (0, 0) * Sigma of Gaussian decay in x and y direction in window CS',
                '        #     Scaling = 1',
                '        #   )',
                '        # )',
                '      )',
                '      # Window("W1")(...) * for multiple window definitions give a name.',
                '    )',
            ],
        },
        'OpticalGeneration': {
            desc: 'Optical generation (basic)',
            lines: [
                '    OpticalGeneration (',
                '      QuantumYield( * conversion model of absorbed photons to generated charge carriers',
                '        StepFunction( * 1 photon = 1 carrier upto "bandgap"',
                '          Bandgap # EffectiveBandgap | Wavelength = ... * [um] | Energy = ... * [eV]',
                '        )',
                '      )',
                '      ComputeFromMonochromaticSource(scaling=1) * set wavelength&intensity in excitation section.',
                '      # ComputeFromSpectrum(',
                '      #   keepSpectralData * keep spectral results when calculating optics. Use File{SpectralPlot = ""}.',
                '      #   Select(. * select a set of entries from spectrum file.',
                '      #     Condition = "0.3 <= $wavelength && $wavelength <= 1.2" * boolean tcl-expression, e.g. select wavelength range. ',
                '      #   )',
                '      #   Scaling = ${1:factor} * scaling factor applied only for quasistationary. Default is 1.',
                '      # )',
                '    )',
            ],
        },
        'OpticalGeneration (Advanced)': {
            desc: 'Optical generation (advanced with spectrum and transient)',
            lines: [
                '    OpticalGeneration (',
                '      QuantumYield( * conversion model of absorbed photons to generated charge carriers',
                '        # Unity * default, 1 photon = 1 carrier',
                '        StepFunction( * 1 photon = 1 carrier upto "bandgap"',
                '          Bandgap # EffectiveBandgap | Wavelength = ... * [um] | Energy = ... * [eV]',
                '        )',
                '        # EffectiveAbsorption * used for FCA.',
                '      )',
                '      ComputeFromMonochromaticSource * set wavelength&intensity in excitation section.',
                '      ComputeFromSpectrum * spectrum defined in File{IlluminationSpectrum = "..."}',
                '      # ComputeFromSpectrum(',
                '      #   keepSpectralData * keep spectral results when calculating optics. Use File{SpectralPlot = ""}.',
                '      #   Select(. * select a set of entries from spectrum file.',
                '      #     Condition = "0.3 <= $wavelength && $wavelength <= 1.2" * boolean tcl-expression, e.g. select wavelength range. ',
                '      #   )',
                '      #   Scaling = ${1:factor} * scaling factor applied only for quasistationary. Default is 1.',
                '      #                      * Also valid for ComputeFromMonochromaticSource, ReadFromFile.',
                '      #   TimeDependence( * scaling factor applied only for transient. Also Valid for ComputeFromMonochromaticSource, ReadFromFile',
                '      #     Scaling = ${1:factor} * sets the pulse height, default is 1.',
                '      #     WaveTime = (${2:t1}, ${3:t2}) * [s] sets start and end time of the pulse plateau.',
                '            * set only one of the following options to set the pulse shape:',
                '      #     WaveTlin   = ${4:tlin}   * [s] sets rise and fall time of a trapezoidal pulse.',
                '      #     WaveTSlope = ${5:tlin}   * [1/s] sets the slope of rise and fall part of a trapezoidal pulse.',
                '      #     WaveTsigma = ${6:tsigma} * [s] sets sigma of the rise and fall part for a gaussian pulse.',
                '      #     WaveTexp   = ${7:texp}   * [s] sets pulse width at 1/e of the rise and fall part for an exponential pulse.',
                '      #     WaveTcos   = ${8:tcos}   * [s] sets pulse width of the rise and fall part for an cosine pulse.',
                '      #     FromFile              * reads time dependence from File {OptGenTransientScaling = "..."}',
                '      #     WavePeriods = ${9:Nperiod} * number of pulses, default = 1',
                '      #     WaveTPeriod = ${10:Tperiod} * [s] period of periodic signal (Nperiod>1).',
                '      #     -OpticalTurningPoints   * switch off automatic discretization of pulse in time.',
                '      #   )',
                '      # )',
                '      ReadFromFile( * reads in external optical generation from File{OpticalGenerationInput = "..."}',
                '        Datasetname = AbsorbedPhotonDensity # | OpticalGeneration * selects which dataset to read from file.',
                '      )',
                '      SetConstant = ${11:G} * [1/cm3s] sets constant generation rate, typically used in regionwise Physics section.',
                '      # -AutomaticUpdate * calls optical solver only on explicit Optics in the solve section.',
                '    )',
            ],
        },
        'OpticalSolver-OptBeam': {
            desc: 'Optical solver OptBeam (basic)',
            lines: [
                '    OpticalSolver(',
                '      OptBeam(',
                '        LayerStackExtraction() * defines line to extract 1D layer structure',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-OptBeam (Advanced)': {
            desc: 'Optical solver OptBeam (advanced)',
            lines: [
                '    OpticalSolver(',
                '      OptBeam(',
                '        LayerStackExtraction( * defines line to extract 1D layer structure',
                '          # Position = (x,y,z) * sets starting point of layer extraction line.',
                '          # WindowName = "${1:window}" * sets window name, when multiple illumination windows are used.',
                '          Mode = Regionwise # | Elementwise * latter used for spatial dependent n&k',
                '          # ComplexRefractiveIndexThreshold = 0.01 * threshold to merge spatial dep. n,k elements into a single layer',
                '        )',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-Raytracer': {
            desc: 'Optical solver RayTracing (basic)',
            lines: [
                '    OpticalSolver(',
                '      RayTracing(',
                '        DepthLimit = 1e4 * sets max # of hitting an interface, emergency stop, use large #!',
                '        MinIntensity = 1e-4 * major stop criteria, when ray intensity reaches this threshold.',
                '        MonteCarlo * activates Monte Carlo algorithm',
                '        PlotInterfaceFlux * active plotting of photon flux through BCs.',
                '        RayDistribution(',
                '          Mode = Autopopulate # | MonteCarlo * equidistant or stochastic start positions',
                '          NumberOfRays = 1000',
                '        )',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-Raytracer (Advanced)': {
            desc: 'Optical solver RayTracing (advanced with farfield)',
            lines: [
                '    OpticalSolver(',
                '      RayTracing(',
                '        DepthLimit = 1e4 * sets max # of hitting an interface, emergency stop, use large #!',
                '        MinIntensity = 1e-4 * major stop criteria, when ray intensity reaches this threshold.',
                '        MonteCarlo * activates Monte Carlo algorithm',
                '        PlotInterfaceFlux * active plotting of photon flux through BCs.',
                '        RayDistribution(',
                '          Mode = Autopopulate # | MonteCarlo * equidistant or stochastic start positions',
                '          NumberOfRays = 1000',
                '          # Mode = Equidistant * specify equidistant ray starting position spaced dx,dy from each other.',
                '          # Dx = ${1:dx}',
                '          # Dy = ${2:dy}',
                '          # WindowName = "${3:window}" * for multiple illumination windows',
                '        )',
                '        Farfield( * plot farfield to File{}',
                '          Discretization = 360',
                '          Sensor( * plot integrated farfield intensity to plt file.',
                '            Angular( * integrate +z half-hemisphere',
                '              Phi = (0 360) * 0 at x-axis, towards y.',
                '              Theta = (0 90) * 3D only: 0 at z-axis, towards xy-plane.',
                '            )',
                '          )',
                '        )',
                '        # RedistributeStoppedRays * redistribute stopped ray intensity into raytree',
                '        # WeightedOpticalGeneration * smoother optical generation when interpolating from element to vertex.',
                '        # OmitReflectedRays * trace transmitted rays only',
                '        # RetraceCRIChange = 0.01 * fractional change in CRI to retrace',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-TMM': {
            desc: 'Optical solver TMM (basic)',
            lines: [
                '    OpticalSolver(',
                '      TMM(',
                '        IntensityPattern = StandingWave # | Envelope * use latter for coarse meshing & layer thickness > 5*wavelength.',
                '        LayerStackExtraction( * defines line to extract 1D layer structure',
                '          Medium( * sets n&k for bottom (top) half-infinite medium',
                '            Location = bottom # | top',
                '            Material = "${1:material}"',
                '          )',
                '        )',
                '      )',
                '    )',
            ],
        },
        'OpticalSolver-TMM (Advanced)': {
            desc: 'Optical solver TMM (advanced with medium options)',
            lines: [
                '    OpticalSolver(',
                '      TMM(',
                '        IntensityPattern = StandingWave # | Envelope * use latter for coarse meshing & layer thickness > 5*wavelength.',
                '        LayerStackExtraction( * defines line to extract 1D layer structure',
                '          Medium( * sets n&k for bottom (top) half-infinite medium',
                '            Location = bottom # | top',
                '            Material = "${1:material}"',
                '            # RefractiveIndex = ${2:n}',
                '            # ExtinctionCoefficient = ${3:k}',
                '          )',
                '          # Position = (x,y,z) * sets starting point of layer extraction line.',
                '          # WindowName = "${4:window}" * sets window name, when multiple illumination windows are used.',
                '          # Mode = Regionwise # | Elementwise * latter used for spatial dependent n&k)',
                '          # ComplexRefractiveIndexThreshold = 0.01 * threshold to merge spatial dep. n,k elements into a single layer',
                '        )',
                '      )',
                '    )',
            ],
        },
    },
    Plot: {
        'Basic-Set': {
            desc: 'Basic set of plot output variables',
            lines: [
                '  eDensity hDensity ',
                '  Current eCurrent  hCurrent',
                '  Potential  SpaceCharge  ElectricField',
                '  eMobility  hMobility  eVelocity  hVelocity',
                '  Doping DonorConcentration AcceptorConcentration',
            ],
        },
        'Extensive-Set': {
            desc: 'Extensive set of plot output variables',
            lines: [
                '  *- Carrier Densities:',
                '  eDensity hDensity',
                '  # EffectiveIntrinsicDensity IntrinsicDensity',
                '  # eEquilibriumDensity hEquilibriumDensity',
                '  *- Currents and current components:',
                '  Current/Vector eCurrent/Vector hCurrent/Vector',
                '  # ConductionCurrent/Vector DisplacementCurrent/Vector',
                '  eMobility hMobility',
                '  eVelocity hVelocity',
                '  *- Fields, Potentials and Charge distributions',
                '  ElectricField/Vector',
                '  Potential',
                '  eQuasiFermi hQuasiFermi',
                '  SpaceCharge',
                '  *- Driving forces',
                '  eGradQuasiFermi/Vector hGradQuasiFermi/Vector',
                '  eEparallel hEparallel ',
                '  eENormal hENormal',
                '  # eEffectiveField hEffectiveField',
                '  *- Temperatures',
                '  LatticeTemperature',
                '  eTemperature hTemperature',
                '  *- Generation/Recombination',
                '  SRHRecombination Band2BandGeneration AugerRecombination RadiativeRecombination',
                '  AvalancheGeneration eAvalancheGeneration hAvalancheGeneration',
                '  TotalRecombination',
                '  eLifeTime hLifeTime',
                '  SurfaceRecombination',
                '  # CDL CDL1 CDL2 CDL3',
                '  # eCDL1lifetime eCDL2lifetime hCDL1lifetime hCDL2lifetime',
                '  # SurfaceMultRecombination',
                '  *- Doping Profiles',
                '  Doping ',
                '  DonorConcentration AcceptorConcentration',
                '  # AntimonyConcentration ArsenicConcentration BoronConcentration ',
                '  # IndiumConcentration NitrogenConcentration PhosphorusConcentration',
                '  # NDopantConcentration PDopantConcentration',
                '  *- Incomplete ionization',
                '  # AsPlus PhPlus SbPlus NitrogenPlus',
                '  # BMinus InMinus ',
                '  # NDopantPlus PDopantMinus ',
                '',
                '  *- Band structure',
                '  BandGap ',
                '  BandGapNarrowing',
                '  ElectronAffinity',
                '  ConductionBandEnergy ValenceBand',
                '  eQuantumPotential hQuantumPotential',
                '  *- Composition',
                '  # xMoleFraction yMoleFraction',
                '  *- Traps',
                '  # eTrappedCharge hTrappedCharge',
                '  # eGapStatesRecombination hGapStatesRecombination',
                '  *- Optical Generation',
                '  # ComplexRefractiveIndex AbsorbedPhotonDensity OpticalGeneration',
                '  # OpticalAbsorptionHeat QuantumYield',
                '  *- Generation due to Ion Strikes',
                '  # AlphaCharge HeavyIonChargeDensity',
                '  *- Gate Tunneling/Hot carrier injection',
                '  # FowlerNordheim ',
                '  # HotElectronInjection HotHoleInjection',
                '  *- Tunneling',
                '  # BarrierTunneling eBarrierTunneling hBarrierTunneling',
                '  # eDirectTunnelCurrent hDirectTunnelCurrent',
                '  *- Ionization Integrals',
                '  # MeanIonIntegral eIonIntegral hIonIntegral ',
                '  *- Heat flow',
                '  # TotalHeat eJouleHeat hJouleHeat',
                '  # PeltierHeat ThomsonHeat RecombinationHeat',
                '  # ThermalConductivity ',
                '  *- Stress-Tensor',
                '  # Stressxx Stressxy Stressxz Stressyy Stressyz Stresszz',
                '  *- Ferro-electrical Polarization',
                '  # Polarization/Vector',
                '  *- Piezo',
                '  # PiezoCharge ConversePiezoelectricField',
                '  # ConversePiezoelectricFieldXX ConversePiezoelectricFieldXY ConversePiezoelectricFieldXZ',
                '  # ConversePiezoelectricFieldYY ConversePiezoelectricFieldYZ ConversePiezoelectricFieldZZ',
            ],
        },
    },
    Solve: {
        'Initial-Solve': {
            desc: 'Initial coupled solve (Poisson, then with carriers)',
            lines: [
                '  Coupled (Iterations= 100 LineSearchDamping= 1e-4){ Poisson ',
                '    * Other common options:',
                '    # eQuantumPotential hQuantumPotential',
                '  } ',
                '  Coupled (Iterations= 100){ Poisson Electron Hole',
                '    * Other common options: ',
                '    # eQuantumPotential hQuantumPotential eTemperature hTemperature Temperature',
                '  } ',
                '  Coupled (Iterations= 100){ Poisson Electron Hole Contact Circuit}',
            ],
        },
        QuasiStat: {
            desc: 'Quasistationary sweep (gate/drain voltage)',
            lines: [
                '  # NewCurrentFile="${1:filename-stem}"',
                '  Quasistationary ( ',
                '    InitialStep= 1e-2 Increment= 1.41',
                '    MinStep= 1e-7     MaxStep= 0.2',
                '    Goal { Name="${2:name}" Voltage= ${3:value} }',
                '  ){',
                '    Coupled { ',
                '      Poisson Electron Hole',
                '      # eQuantumPotential hQuantumPotential',
                '      # eTemperature hTemperature Temperature',
                '      # Contact Circuit',
                '    }',
                '    # CurrentPlot(Time=(Range=(0 1) Intervals=30))',
                '  }',
            ],
        },
        Transient: {
            desc: 'Transient simulation',
            lines: [
                '  # NewCurrentFile="${1:filename-stem}"',
                '  Transient (',
                '    InitialTime= ${2:value [s]} FinalTime= ${3:value [s]}',
                '    InitialStep= ${2:value [s]} Increment= 1.41',
                '    Minstep= ${4:value [s]} MaxStep= ${5:value [s]}',
                '  ){',
                '    Coupled {',
                '      Poisson Electron Hole',
                '      # eQuantumPotential hQuantumPotential',
                '      # eTemperature hTemperature Temperature',
                '      # Contact Circuit',
                '    }',
                '  }',
            ],
        },
        ACcoupled: {
            desc: 'AC coupled small-signal analysis',
            lines: [
                '  Quasistationary (',
                '    InitialStep= 1e-2 Increment= 1.41',
                '    MinStep= 1e-7     MaxStep= 0.2',
                '    Goal { Parameter=${1:name}.dc Voltage= ${2:value} }',
                '  ){',
                '    ACCoupled (',
                '      StartFrequency= ${3:value [Hz]} EndFrequency= ${4:value [Hz]}',
                '      NumberOfPoints= ${5:int} [Decade | Linear]',
                '      Node(${6:list-of-nodes}) Exclude(${7:list-of-voltage-source-names}) ',
                '      ACCompute (Time = (Range = (0 1)  Intervals = ${5:int}))',
                '    ){',
                '      ${8:equations}',
                '    }',
                '  }',
            ],
        },
    },
    System: {
        System: {
            desc: 'System section for circuit, voltage sources, and devices',
            lines: [
                'File {',
                '  Output= "@log@"',
                '}',
                '',
                'Device ${1:dev-name} {',
                '  Electrode { ... }',
                '  File { ... }',
                '  Physics { ... }',
                '}',
                '',
                'System {',
                '  *- Voltage sources',
                '  Vsource_pset ${2:v-name} (${3:node1} ${4:node2}) { dc= ${5:value [V]} }',
                '  Vsource_pset ${2:v-name} (${3:node1} ${4:node2}) { ',
                '    pulse= (${5:value [V]}   * dc-offset',
                '      ${6:value [V]}   * amplitude',
                '      ${7:value [s]}   * td: initial delay',
                '      ${8:value [s]}   * tr: rise time',
                '      ${9:value [s]}   * tf: fall time',
                '      ${10:value [s]}   * pw: pulse width or duration',
                '      ${11:value [s]})  * period',
                '  }',
                '  Vsource_pset ${2:v-name} (${3:node1} ${4:node2}) { ',
                '    pwl= ( ${12:t1 [s]} ${13:v1 [V]}  ${14:t2 [s]} ${15:v2 [V]} [...] )',
                '  }',
                '  *- Physical devices ',
                '  ${1:dev-name} ${16:instance-name} ( "${17:cont1}"= ${3:node1}  "${18:cont2}"= ${4:node2} [...] )',
                '  *- Lumped elements',
                '  Capacitor_pset ${19:c-name} ( ${3:node1} ${4:node2} ){ capacitance= ${20:value [C]} }',
                '  Resistor_pset  ${21:r-name} ( ${3:node1} ${4:node2} ){ resistance= ${22:value [Ohm]} }',
                '  Inductor_pset  ${23:i-name} ( ${3:node1} ${4:node2} ){ inductance= ${24:value [H]} }',
                '  *- Plotting',
                '  Plot "${25:file-name}.plt" (time() v(${26:node}) i(${27:element},${26:node}) [...] )',
                '}',
            ],
        },
    },
};
